/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./components/LogInDialog copy.vue')['default']
    EditEntryForm: typeof import('./components/EditEntryForm.vue')['default']
    EntryList: typeof import('./components/EntryList.vue')['default']
    LogInDialog: typeof import('./components/LogInDialog.vue')['default']
    NoEntriesMessage: typeof import('./components/NoEntriesMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
